### ISSUE TITLE
Feature: advise of connection progress

### ISSUE THREAD

**Issue by quozl** [sugarlabs/chat#16]
When a second or subsequent instance of the activity is started by others, there is little explanation for the delay that ensues.  Like the Maze activity says "Joining a maze", say "Joining a chat" or whatever message is appropriate given the other messages in use now.

**Comment by Aniket21mathur** [comment]
`Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 219, in <module>
    main()
  File "/usr/bin/sugar-activity", line 163, in main
    module = __import__(module_name)
  File "/home/guest/GSOC/test/chat/activity.py", line 22, in <module>
    gi.require_version('TelepathyGLib', '0.12')
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace TelepathyGLib not available
`
I am getting this error on running the activity.Please help.
Thanks!

**Comment by quozl** [comment]
* your comment has nothing to do with the issue, and is a distraction for the issue, so I'll be deleting it; in future please ask such questions on sugar-devel@ mailing list,
* you are missing a software package on your system; `gir1.2-telepathyglib-0.12` for Debian or Ubuntu.
