### ISSUE TITLE
Feature: searching

### ISSUE THREAD

**Issue by quozl** [sugarlabs/chat#18]
One of the original design features not yet implemented is searching.

* [x] add a search widget to the tool bar with shortcut <kbd>ctrl+f</kbd> which highlights the first result and if necessary changes the scrollback position to do so,
* [x] add a search next widget with shortcut <kbd>ctrl+g</kbd>,
* [x] add a search previous widget with shortcut <kbd>shift+ctrl+g</kbd>,
* [x] add a activity shortcut <kbd>esc</kbd> which is to cancel the search and restore previous position,

Reference: http://wiki.laptop.org/go/Chat

**Comment by nswarup14** [comment]
@quozl 
Wouldn't it better if the chat history was preserved in the journal entry itself?
As I understand, the proposed search feature is to highlight the relevant text that matches with the search query in the chat activity itself.

Assuming a chat room with 4 participants, if one of them happens to leave, the chat log is stored in the journal. If the participant later opens the journal object, the earlier chat log is loaded, as expected. Thus we are able to achieve persistence storage, even if the participants continue to leave and rejoin as many number of times. 

The only time the chat log is lost is when the journal object is deleted. This is once again expected, but we needn't store the chat log of an activity instance whose journal object is deleted.

Unless I have misunderstood the proposed feature itself, I feel that preserving chat in the journal entry is sufficient. Please feel free to correct me.

Thanks

**Comment by quozl** [comment]
Thanks for thinking about this.  I neglected to fully express my thinking or think through the reasons.  I've edited the initial comment.

**Comment by quozl** [comment]
1ecad5a merged without complete position support.
