### ISSUE TITLE
Prevent user from sending smileys when disconnected

### ISSUE THREAD

**Issue by shaansubbaiah** [sugarlabs/chat#30]
Users are able to send smileys when disconnected. Like sending text, sending smileys should also be disabled when the user isn't connected.

**Tested on:**
	Sugar 0.117-3, Debian Bullseye
	Sugar 0.117, Sugar Live Build
	OLPC OS 18.04

**Comment by chimosky** [comment]
By disconnected you mean when activity isn't shared?

**Comment by shaansubbaiah** [comment]
> By disconnected you mean when activity isn't shared?

Yes, when it isn't shared.

**Comment by chimosky** [comment]
Just took a look and the emojis can't be sent but they do appear in the text box.

**Comment by chimosky** [comment]
My bad, they can be sent with the button beside the text box and not the entry key.

**Comment by shaansubbaiah** [comment]
Like the text box, can the Smiley button's sensitivity be set to disabled when the Activity is not shared?

**Comment by chimosky** [comment]
Yes all buttons should be insensitive when the activity isn't shared.
