### ISSUE TITLE
Issue with user mode switching

### ISSUE THREAD

**Issue by XXXJumpingFrogXXX** [sugarlabs/chat#38]
When the connection to the chat room status (multiuser mode) is activated, it is not possible to click the button on the left to return to single-user mode; the only option is to exit the chat room.
![Uploading image.png…]()

**Comment by quozl** [comment]
Yes, Sugar toolkit has a "once shared always shared" feature for activity collaboration.  A journal entry that is shared cannot transition back to one that is not.  Chat activity uses the same collaboration infrastructure.

**Comment by quozl** [comment]
To regain privacy, right-click on the Chat icon in the Home view and select _Start new_.
