### ISSUE TITLE
Security Enhancement

### ISSUE THREAD

**Issue by 12sachingupta** [sugarlabs/chat#43]
Conduct a security audit to identify potential vulnerabilities in the chatbot integration and implement measures to safeguard user data and privacy.

**Comment by chimosky** [comment]
Chatbot is nonexistent at the moment, we can't conduct a security audit for something that doesn't exist.

**Comment by 12sachingupta** [comment]
Sir , It Is basically about GSOC
I am choose the project Chatbot for chat Activity.
My GSOC Proposal : https://summerofcode.withgoogle.com/media/user/8b1c18073f4e/proposal/gAAAAABmBUd04x2An86FbUuLNjQLia9ehwkNug6DKkkexcEhfM1v4ZbrQI52tN6mO7hdkKi-_Jtzxmex5IPJa_37lrOShNyF6Dbx8mC9ZGc-VnBD6_r9gyU=.pdf

@chimosky sir please give me feedback about it.
